### ISSUE TITLE
Improve behaviour of Search to support repeated searches

### ISSUE THREAD

**Issue by lyricnz** [cointop-sh/cointop#187]
At the moment, if you're looking for a substring, or a duplicated value, the behaviour of the search function is a bit unintuitive:
- it's a bit unclear how search is working vs Symbol/Name and how the fuzzy search works
- searching always starts at the top, regardless of current position
- multiple matches are hidden / cannot find

**Comment by lyricnz** [comment]
Demo of repeatedly searching for "bi" (/bi[enter] then /[enter])

https://user-images.githubusercontent.com/122371/136876648-269c0de1-679b-461d-913c-38eee8e8771b.mov

**Comment by miguelmota** [comment]
Closing since technically the merged PR solves supporting repeated searches
