### ISSUE TITLE
Global Market Cap chart shows in USD regardless of currency conversion

### ISSUE THREAD

**Issue by simon-anz** [cointop-sh/cointop#208]
Made worse by #207 (currency not shown on screen)
![Screen Shot 2021-10-08 at 2 09 07 pm](https://user-images.githubusercontent.com/69175652/136492262-4cf74621-506a-4f9f-9acd-bb883568f089.png)

**Comment by simon-anz** [comment]
We appear to be using non-API call 
https://www.coingecko.com/market_cap/total_charts_data?duration=7&locale=en&vs_currency=usd
Which doesn't obey vs_currency

**Comment by lyricnz** [comment]
Fixed

**Comment by lyricnz** [comment]
Sent email to coingecko about how to access this data via an API, not web-url.
