### ISSUE TITLE
Remove all mouse bindings

### ISSUE THREAD

**Issue by matthiasbeyer** [cointop-sh/cointop#241]
Is there a way to remove mouse recognition?

Usecase is simple: I'd like to open cointop and then make my terminal (Konsole) read-only. For that I'd like to use right-click (to open the konsole menu and select "Read-only").

Right now that is not possible because cointop captures the mouse click.

**Comment by lyricnz** [comment]
Raised a PR to make this configurable. Feel free to checkout and build, and see if it works for you?
