### ISSUE TITLE
Docker not yet updated

### ISSUE THREAD

**Issue by skiwithpete** [cointop-sh/cointop#262]
Sorry to be the guy who always asks that the docker be updated.  But I use that... so I need it 

;)

Thanks for making such a great app.

P

**Comment by lyricnz** [comment]
We will try and add some automation to publish new docker images with each release.

**Comment by miguelmota** [comment]
Thanks for the heads up again @skiwithpete 

The `:latest` docker tag will now [autobuild](https://github.com/cointop-sh/cointop/commit/4fa9a85f0cfb99bf11253a563582930db0973e20) when the `master` branch is updated

![DeepinScreenshot_select-area_20211107142521](https://user-images.githubusercontent.com/168240/140664035-d738fd84-036c-4262-b928-2f59e521ae90.png)
![DeepinScreenshot_select-area_20211107142532](https://user-images.githubusercontent.com/168240/140664036-076d9eb7-e76a-4e41-a1b6-d41a06bd3450.png)

**Comment by lyricnz** [comment]
https://hub.docker.com/r/cointop/cointop/tags

**Comment by lyricnz** [comment]
I think this can be closed
