### ISSUE TITLE
Desktop notifications for alerts?

### ISSUE THREAD

**Issue by lyricnz** [cointop-sh/cointop#268]
Coming upstream https://github.com/gdamore/tcell/issues/499

**Comment by miguelmota** [comment]
How would this differ from https://github.com/gen2brain/beeep?

which cointop currently has integrated for alert notifications

https://github.com/cointop-sh/cointop/blob/0bacbe5b9d83f9b9cff033f80e081146b4cc4bdb/pkg/notifier/notiifer.go#L9

**Comment by lyricnz** [comment]
Ah does it?  I never noticed it (or use alerts at all). Was just browsing the tcell issue queue.

**Comment by lyricnz** [comment]
Will add to features in README. Closing this issue
