### ISSUE TITLE
readme error?

### ISSUE THREAD

**Issue by alexzanderr** [cointop-sh/cointop#272]
what do you mean with this?
```
ssh cointop.sh
```

did you mean this?
```
sh cointop.sh
```

**Comment by miguelmota** [comment]
It's a server anyone can ssh into to try cointop

https://twitter.com/cointop/status/1330961389951729669?s=20

**Comment by lyricnz** [comment]
Added a clarification to README about this being an online instance. #273

**Comment by alexzanderr** [comment]
wooow, soo cool.
its a domain name with ip address (https://cointop.sh/). my bad. sorry for this issue.
