### ISSUE TITLE
Open custom link with a symbol

### ISSUE THREAD

**Issue by n1s** [cointop-sh/cointop#283]
Hi,

How about introducing opening custom link with hotkey Shift+O with %s placeholder containing coin symbol.

For example I would like to open tradingview chart - the link is as follows
https://www.tradingview.com/chart/?symbol=BITSTAMP%3ABTCUSD

so in cointop this could be 
https://www.tradingview.com/chart/?symbol=%sUSDT

so it opens
https://www.tradingview.com/chart/?symbol=ADAUSDT
when cardano is highlighted

I think this could be helpful feature

**Comment by lyricnz** [comment]
Maybe we could implement this using a format-string given the context of the Coin, fix maximum flexability.  

customLinkFormat: "https://www.tradingview.com/chart/?symbol={coin.Symbol}USDT"

That way we can potentially use other attributes of Coin (name, id, price, holdings, etc) if required...

**Comment by lyricnz** [comment]
Would you need this in addition to the current "open in browser" capability, or would this be an alternate/configurable target?

**Comment by lyricnz** [comment]
Have a gander at #284

**Comment by miguelmota** [comment]
Example link in config

```toml
alt_coin_link = "https://www.tradingview.com/symbols/{{SYMBOL}}USD/"
```

Available tags:
- `{{ID}}`
- `{{NAME}}`
- `{{RANK}}`
- `{{SLUG}}`
- `{{SYMBOL}}`

**Comment by miguelmota** [comment]
Closed by https://github.com/cointop-sh/cointop/pull/284
