### ISSUE TITLE
Can't delete Ethereum Cash from my portfolio

### ISSUE THREAD

**Issue by blogdemoi** [cointop-sh/cointop#287]
Hello,

I cannot delete Ethereum Cash from my portfolio for a mysterious reason. I can delete all other coins in my portfolio except this one.

I installed Cointop on my Manjaro using this AUR https://aur.archlinux.org/packages/cointop/#news and signaled this problem on the web page but there is no response, so I am wondering if this is a cointop issue or a AUR packaging one...

Thank you.

**Comment by lyricnz** [comment]
Which version of cointop is it?  What does the holdings line look like in your config.toml?

**Comment by lyricnz** [comment]
It looks like it's 1.6.9?

**Comment by blogdemoi** [comment]
Sorry, yes the version is 1.6.9.

The holding lines are: 

[portfolio]
  columns = ["rank", "name", "symbol", "price", "holdings", "balance", "1h_change", "24h_change", "7d_change", "percent_holdings", "last_updated"]
  compact_notation = false
  holdings = [["Axie Infinity", "xxx"], ["Binance Coin", "xxx"], ["Bitcoin", "xxx"], ["Bitcoin Cash", "xxx"], ["Bitcoin Gold", "xxx"], ["Cardano", "xxx"], ["Chainlink", "xxx"], ["DeRace", "xxx"], ["Defina Finance", "xxx"], ["Dogecoin", "xxx"], ["EOS", "xxx"], ["Elrond", "xxx"], ["Ethereum", "xxx"], ["Ethereum Classic", "xxx"], ["FTX Token", "xxx"], ["Flow", "xxx"], ["Injective Protocol", "xxx"], ["Internet Computer", "xxx"], ["Litecoin", "xxx"], ["Monero", "xxx"], ["Moonriver", "xxx"], ["Polkadot", "xxx"], ["Polygon", "xxx"], ["RMRK", "xxx"], ["Shiba Inu", "xxx"], ["Solana", "xxx"], ["Stellar", "xxx"], ["Swipe", "xxx"], ["TRON", "xxx"], ["Tether", "xxx"], ["Tezos", "0.79"], ["Theta Network", "xxx"], ["Uniswap", "xxx"], ["VeChain", "xxx"], ["XRP", "xxx"], ["eCash", "xxx"]]

I could change the Ethereum Cash to what I hold but now I have a line at the bottom that I don't understand, "Buff Doge Coin" and I can't delete it:
![2021-Friday-November-03-09-30](https://user-images.githubusercontent.com/83965802/142553089-e5d11b0b-448a-40e9-a404-3a7352edb7e7.png)

**Comment by lyricnz** [comment]
Can you delete your cache, and see if Buff Doge is still there?  There were a few issues in this area recently - Buf
#214 #171 #148

**Comment by blogdemoi** [comment]
Thank you, after deleting the cache the "Buff Doge Coin" line disappeared. However I still can't delete Ethereum cash, I can delete all other cryptos in my portfolio except this one.

**Comment by lyricnz** [comment]
Ah. The problem is that "eCash" isn't the correct name for the coin - it's "Ethereum Cash".  I assume you had an existing portfolio and upgraded cointop, which now uses unambiguous coin names, rather than possibly duplicate coin symbols.  You can edit your config file, and change "eCash" to "Ethereum Cash" and everything should be fine.

**Comment by lyricnz** [comment]
Support for referencing coins by Symbol (rather than name) was removed in #219

**Comment by blogdemoi** [comment]
> You can edit your config file, and change "eCash" to "Ethereum Cash" and everything should be fine.

Thank you for your help, it worked.
