### ISSUE TITLE
ctrl+c doesn't work as expected (to exit app) on Windows/Linux

### ISSUE THREAD

**Issue by vuon9** [cointop-sh/cointop#292]
Right now we're binding ^C to tcell.KeyCtrlC + tcell.ModNone
But the event is arriving (on my mac at least) as tcell.KeyCtrlC + tcell.ModControl

^C happens to be hardcoded (ignoring the shortcut config), so we can fix it with a kludge, but the shortcut parsing/binding may need to bind both?

**Comment by lyricnz** [comment]
I guess we need to bind ^C to both key=ControlC,mod=None and key=ControlC,mod=Control

**Comment by lyricnz** [comment]
Probably fixed by #293

**Comment by lyricnz** [comment]
Yup
