### ISSUE TITLE
Portfolio sum all holdings

### ISSUE THREAD

**Issue by danfossi** [cointop-sh/cointop#300]
It would be great if in the [P]ortfolio section there was a way to have the total of all the coin in holdings.

**Comment by lyricnz** [comment]
A total value? That's already there at the top of the screen.

![image](https://user-images.githubusercontent.com/122371/150896985-4c578b4a-2eb5-4f80-b2e8-b236d0433bbb.png)

**Comment by lyricnz** [comment]
You can change the displayed currency (it converts) using the "c" key. Mine is set to AUD.

**Comment by danfossi** [comment]
as not mentioned, it is exactly the feature I was looking for! sorry!

**Comment by lyricnz** [comment]
no problem; thanks for your time
